services:
  - type: web
    name: cashbook-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: cashbook-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: cashbook-backend-2.onrender.com,*.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"

databases:
  - name: cashbook-db
    databaseName: cashbook_os9o
    user: cashbook

